server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb2
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: CUSTOMERINQUIRY-SERVICE

